### ISSUE TITLE
[Segmentation fault] when files manager plugin is disabled

### ISSUE THREAD

**Issue by pierretom** [Mezomish/juffed#82]
Hello,

Commit: 54b9cb47a6c7e2a4918af277c66a00068e012087
Date: Tue Nov 17 07:29:30 2015 +0100
Qt version: 5.5.1

Here a backtrace:

```
(gdb) r
Starting program: /usr/local/bin/juffed 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffeb6ac700 (LWP 7151)]
"[18:23:41]" "--- Plugin 'Autosave' is disabled in Settings."
"[18:23:41]" "--- Plugin 'Color Picker' is disabled in Settings."
"[18:23:41]" "+++ Plugin 'Documents List' was loaded successfully."
"[18:23:41]" "+++ Plugin 'Favorites' was loaded successfully."
QObject::connect: No such signal FindWorker::terminated()
"[18:23:41]" "+++ Plugin 'Find In Files' was loaded successfully."
[New Thread 0x7fffe24e1700 (LWP 7152)]
"[18:23:41]" "--- Plugin 'File manager' is disabled in Settings."
"[18:23:41]" "+++ Plugin 'Keybindings' was loaded successfully."
"[18:23:41]" "+++ Plugin 'Sort Document' was loaded successfully."
"[18:23:41]" "+++ Plugin 'Symbol_browser' was loaded successfully."
"[18:23:41]" "+++ Plugin 'XML Formatter' was loaded successfully."
"[18:23:41]" "Session '/home/pierre/.config/juff/sessions/_empty_session_' opened successfully"
"[18:23:41]" "Session '/home/pierre/.config/juff/sessions/_empty_session_' was parsed successfully"

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7385b28 in QWidget::ensurePolished() const () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
(gdb) bt
#0  0x00007ffff7385b28 in QWidget::ensurePolished() const () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#1  0x00007ffff7385baf in QWidget::ensurePolished() const () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#2  0x00007ffff738a568 in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#3  0x00007ffff7346ffc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#4  0x00007ffff734c4c6 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#5  0x00007ffff6a53b6b in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007ffff6a55f66 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007ffff6aa9ed3 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007ffff4abcfd7 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#9  0x00007ffff4abd230 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#10 0x00007ffff4abd2dc in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007ffff6aaa2df in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#12 0x00007ffff6a512fa in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#13 0x00007ffff6a593dc in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x0000000000450ea4 in runSingle (argc=1, argv=0x7fffffffe8e8) at /home/pierre/git/juffed/src/app/main.cpp:164
#15 0x0000000000451177 in main (argc=1, argv=0x7fffffffe8e8) at /home/pierre/git/juffed/src/app/main.cpp:186
```

**Comment by q4a** [comment]
This should be fixed with: https://github.com/Mezomish/juffed/commit/718e2c7883167f2f94d7744208a9c59d0437ac87
